require("tony.plugins-setup")
require("tony.core.options")
require("tony.core.keymaps")
require("tony.core.colorscheme")
require("tony.plugins.comment")
require("tony.plugins.nvim-tree")
require("tony.plugins.lualine")
require("tony.plugins.telescope")
